### ISSUE TITLE
Error Bot

### ISSUE THREAD

**Issue by Jqrne** [Necrobot-Private/NecroBot#1216]
### My Log:
```
[11:02:41] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Extensions\HttpClientExtensions.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__4`2.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\Player.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\Login.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()


Version:
Windows Version: Windows 7
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): 
The bot isnt starting up. I already used the bot for over a week, I wanted to start it up today and  it wouldnt work.

**Comment by zsw12abc** [comment]
same here

**Comment by deathclaw123** [comment]
api outdated

**Comment by Jqrne** [comment]
How can i update it?

**Comment by Jqrne** [comment]
And the bot wont login to my account, I forgot to mention that.

**Comment by Liferuiner96** [comment]
same problem here.
please fix it!

**Comment by sakaba001** [comment]
Make sure that you already have the .134 version

**Comment by sakaba001** [comment]
And if you still using legacy .45 api, it's currently having problem and not have been fixed yet

**Comment by yayahai** [comment]
There has been an API update. Use the latest version of necrobot v.134.

**Comment by Jqrne** [comment]
Do i have to download it again ?

**Comment by Jqrne** [comment]
Because i downloaded the update.

**Comment by Liferuiner96** [comment]
i have downloaded the latest version already but still the same problem

**Comment by yayahai** [comment]
If you're using the free 0.45 API , you'll have to wait. Moreover , using 0.45 Api is a sure shot way of getting banned.

**Comment by deathclaw123** [comment]
https://checkout.shopify.com/14884872/checkouts/7406e8c47cf91f62d0919c88f2774af5?token=EC-9JU753670H929151L buy this and rock

**Comment by deathclaw123** [comment]
it will run 3 bot in same time

**Comment by deathclaw123** [comment]
and no ban

**Comment by Liferuiner96** [comment]
and it works right now?

**Comment by Jqrne** [comment]
Can you re-make the script like you want to if you buy Pgodev?

**Comment by Liferuiner96** [comment]
how long do i have to wait if i use the free API?

**Comment by Hydrojw1** [comment]
Will the new verison of bot work with the API from Bossland? Are they in synch with each other because the Bossland site is not very friendly with info about the API

**Comment by cocacolabanane** [comment]
Please fix thanks to uploader

**Comment by cocacolabanane** [comment]
The bot goes back to one

**Comment by deathclaw123** [comment]
@cocacolabanane is it working?

**Comment by deathclaw123** [comment]
@Hydrojw1 yes it will work

**Comment by FaMeMaJic** [comment]
i have the same Problem -.- new update is not working i have buy today a key ....

then i have downloaded the old Version it not workinh beacouse KILLSWITCH and api its not goo

#77216

**Comment by LimitedOC** [comment]
i also have that problem so am not the only one. i was ready to make a post about it but i dont think it will be needed. please a dev needs to give an answer to this error cuz it seems it has nothing to do with us

**Comment by FaMeMaJic** [comment]
I wait some time then we see i have buy today a key this is soooo terrible!

Am 08.03.2017 01:16 schrieb "LimitedOC" <notifications@github.com>:

**Comment by Liferuiner96** [comment]
any news till now?

**Comment by LimitedOC** [comment]
nothing changed still i just tried...

**Comment by FaMeMaJic** [comment]
-,-

Am 08.03.2017 02:03 schrieb "LimitedOC" <notifications@github.com>:

**Comment by cocacolabanane** [comment]
fix go go go go go go go go go go go gogo go go go go go go go

**Comment by Liferuiner96** [comment]
@cocacolabanane  are you sure?

**Comment by FaMeMaJic** [comment]
not fixed

[142832] (FEHLER) Pokemon Servers might be offline  unstable. Trying again...
[142832] (FEHLER) Error System.ComponentModel.Win32Exception (0x80004005) Die angegebene ausführbare Datei ist keine gültige Anwendung für diese Betriebssystemplattform.
   bei System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start()
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei PoGo.NecroBot.Logic.State.VersionCheckState.Executed__3.MoveNext() in cprojectsnecrobot2PoGo.NecroBot.LogicStateVersionCheckState.csZeile 118.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.Startd__3.MoveNext() in cprojectsnecrobot2PoGo.NecroBot.LogicStateStateMachine.csZeile 101.

**Comment by cocacolabanane** [comment]
What is the simple entries delete ??

**Comment by FaMeMaJic** [comment]
bevor coming the uptade it was evething ok -.- 

PLEASE FIXE I WILL USE MY KEY !!!!

**Comment by cocacolabanane** [comment]
not go in clear text or what

**Comment by dirkkrueger** [comment]
https://github.com/Necrobot-Private/NecroBot/blob/c1a6ea20ad6ddeb25def15474308d5003376d7e9/KillSwitch.txt

`BotStatus=DISABLE;
//================================================================//
                POKEMON GO 0.57.4
//================================================================//
We are investigating changes to the authentication that
Niantic made in 0.57.4. So the bot will be temporarily disabled.
//================================================================//
                         Updated: 3/08/2017`

**Comment by Liferuiner96** [comment]
any idea how long it will take?
i mean will it take a few hours? or a few days?

**Comment by dirkkrueger** [comment]
Noboy can know. 
They did a awsome work on that project (Thank you by the way) but maybe niantic did finaly something propper agains Bot like Necro and Bots will never work again.

**Comment by cocacolabanane** [comment]
then the bot builders say what or

**Comment by Hydrojw1** [comment]
Its just an API change, the developers need to understand the chatter before they can ensure the bot can emulate the app. Give it a week or 2.

**Comment by FaMeMaJic** [comment]
And what is with my key .. I bought the today and the runs in 31.? If it lasts 1 to 2 weeks I have only paid for 2 weeks. ==?

**Comment by Hydrojw1** [comment]
Hopefully the bot is fixed soon and your API key will work. Unfortunatly this is what happens when you do things fast.......... how would you feel if the Necrobot team released the bot early, untested and we all get banned?

**Comment by yayahai** [comment]
I am not facing any issues and I am using the latest version with a hashing key. Don't know why you guys are facing problems!

**Comment by cocacolabanane** [comment]
When is the free again ???

**Comment by Liferuiner96** [comment]
it will take some time for them to fix the issues

**Comment by xBattlePigx** [comment]
I found this somewhere. im not sure if its secure to use this API but its working for me. I redownloaded the bot and when it gave me the choice to put the API code in on the same menu where you sign in using your account info. 2F0N1F0P0A5M5E3O1I4X﻿

**Comment by skertwater** [comment]
should i type in yes to override killswitch? Is it safe even with the code? please help me ;(

**Comment by Liferuiner96** [comment]
the normal bot works with that hash key
but are you guys able to snipe pokemon?

it says it coudlnt connect to necro socket server

**Comment by skertwater** [comment]
what do u mean by normal bot

**Comment by Liferuiner96** [comment]
he walks around spinin some pokestops and catch the pokemon at this place but do not snipe any pokemon

**Comment by skertwater** [comment]
so i type in yes to accept the killswitch thingy?

**Comment by LimitedOC** [comment]
ill say this, if u have a high account dont take the risk and use another key. i am like 33 lvl with 6 dragonites over 3k each and i already lost an account (at summer) with ban. so please support our devs and wait for their news. it will be better to wait sometime for 1 2 weeks even than lose a huge account for ever and start over again.

**Comment by skertwater** [comment]
ok i will wait then thank you so much

**Comment by LimitedOC** [comment]
keep this in your mind, nintiatic is after us and wanna eliminate our work. so you have to be extra carefull with them

**Comment by Liferuiner96** [comment]
yeah thank you very much
but i j have tried it with a new account ;) didnt want to risk my main account

**Comment by LimitedOC** [comment]
this is better but you wont be sure until devs will announce it. because you can start another account and get 20 lvls like ez and then think: oh see? nothing changed at all! and log to you main to keep your work up and get banned. you will be never sure so as everyone says: time will heal every wound

**Comment by skertwater** [comment]
do i use this pin to login? 2F0N1F0P0A5M5E3O1I4X﻿

**Comment by skertwater** [comment]
ok now i cant log in beacuse it keeps repeating this blue text wow

**Comment by LimitedOC** [comment]
i told you to wait, you didnt heard me ;p

**Comment by skertwater** [comment]
well i wannted to it on my second account :(

**Comment by hardknoxni69a** [comment]
The free Api is down that's why u get this issue please join our discord for news and announcements the bot does seem to work well with API key but we implemented a killswitch to be safe while we look Into login procedure further botting is risky atm please don't use main account until login security issues has been verified working fully

**Comment by onkarborg** [comment]
the bot still shows me the same error when I use the free 0.45 Legacy API.

**Comment by hardknoxni69a** [comment]
This option doesn't work u need a paid API key only way to bot at the moment
